const bcrypt = require("bcryptjs");
const data = {
  users: [
    {
      name: "Tin Myo Win",
      email: "admin@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "john",
      email: "user1@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/product-1.jpg",
      price: 120,
      countInStock: 9,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Adidas fit Shirt",
      category: "Shirts",
      image: "/images/product-2.jpg",
      price: 160,
      countInStock: 15,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "Gucci Shirt",
      category: "Shirts",
      image: "/images/product-3.jpg",
      price: 240,
      countInStock: 19,
      brand: "Gucci",
      rating: 2.5,
      numReviews: 25,
      description: "high quality product",
    },
    {
      name: "Nike Pants",
      category: "Pants",
      image: "/images/product-5.jpg",
      price: 100,
      countInStock: 0,
      brand: "Nike",
      rating: 4.5,
      numReviews: 12,
      description: "high quality product",
    },
    {
      name: "Long Pants",
      category: "Pants",
      image: "/images/product-6.jpg",
      price: 150,
      countInStock: 1,
      brand: "Nike",
      rating: 4,
      numReviews: 19,
      description: "high quality product",
    },
  ],
};

module.exports = data;
